version: "3"
services:
  app_monolith:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_monolith
    restart: unless-stopped
    tty: true
    ports:
      - "80:1215"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - dev

  db_monolith:
    image: postgres:11
    container_name: db_monolith
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=monolith
      - POSTGRES_PASSWORD=monolith
      - POSTGRES_DB=monolith
    volumes:
      - postgres_11:/var/lib/postgresql/data/
    networks:
      - dev

networks:
  dev:

volumes:
  postgres_11:
    external: true

